// any is not a data type
// rather it tells that type checking for this particular variable is off....
// we should avoid any , because any is not typeChecked....
// (any) avoids all the strictness which typescript brings to our code...
// noImplicitAny flag - use this to flag any implicit any as an error
var hero;
// we can also make conditions on function that it must be return some-specific type and all....
function getHero() {
    return "thor";
}
hero = getHero();
